version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: tfvb_postgres
    restart: always
    volumes:
      - "tfvb_postgresql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: tfvb
      POSTGRES_USER: tfvb
      POSTGRES_PASSWORD: tfvb
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    container_name: tfvb_redis
    ports:
      - "6379:6379"

volumes:
  tfvb_postgresql_data:
